mybatis:
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰与下划线的映射
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 将SQl语句打印到控制台
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/znwl_agriculture?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8081